### ISSUE TITLE
Feature: Permissions for custom pages

### ISSUE THREAD

**Issue by Radiergummi** [psychobunny/nodebb-plugin-custom-pages#12] opened 2015-05-08 09:19 UTC
I just realized guests have no permission to view custom pages. Some kind of control would be great here (in Germany you are obliged to make your contact details public and accessible instantly from any point of your website in under three clicks)

**Comment by frenchja** [comment] 2015-07-05 15:44
There are still controls set at the widget level.  For example, on one custom route, I have registration instructions in a widget set to render for guests only.

**Comment by pitaj** [comment] 2015-09-30 05:32
Duplicate of #7

**Closed** 2017-08-25 20:46 UTC
